---
- hosts: virtualmachines
  vars_files:
    - vars.yaml
  become: yes
  tasks:
    # smoke test and essential dependencies
    - name: ping
      ansible.builtin.ping:
    - name: essentials
      ansible.builtin.apt:
        update_cache: yes
        name:
          - vim
          - git
          - postgresql
          - redis-server
          - python3.9
          - python3.9-venv
          - python3.9-dev
          - libpq-dev
          - gcc
          - python3-psycopg2
        state: present

    # postgresql setup
    - name: pg user
      community.general.postgresql_user:
        name: sfs_user
        password: "{{ pgpassword }}"
        expires: infinity
        state: present
      become_user: postgres
    - name: pg database
      community.general.postgresql_db:
        name: sfs_db
        owner: sfs_user
        state: present
      become_user: postgres
    - name: pg permissions
      community.postgresql.postgresql_privs:
        db: sfs_db
        privs: ALL
        objs: ALL_IN_SCHEMA
        role: sfs_user
        grant_option: true
      become_user: postgres

    # node.js and npm
    - name: add nodesource key
      ansible.builtin.apt_key:
        id: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
        state: present
    - name: add nodesource repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main
    - name: install nodejs
      ansible.builtin.apt:
        update_cache: yes
        name: nodejs
        state: present

    # caddy
    - name: add caddy key
      ansible.builtin.apt_key:
        id: 65760C51EDEA2017CEA2CA15155B6D79CA56EA34
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        keyring: /etc/apt/trusted.gpg.d/caddy-stable.gpg
        state: present
    - name: add caddy deb repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/caddy-stable.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    - name: add caddy deb-src repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/caddy-stable.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    - name: install caddy
      ansible.builtin.apt:
        update_cache: yes
        name: caddy
    - name: caddyfile
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: '0644'

    # deploy user and directory
    - name: www directory
      ansible.builtin.file:
        path: /var/www
        state: directory
        mode: '0755'
    - name: create user
      ansible.builtin.user:
        name: deploy
        password: ""
        shell: /bin/bash
        groups:
          - sudo
          - www-data
        append: yes
        createhome: yes
        skeleton: '/etc/skel'
        generate_ssh_key: yes
        ssh_key_type: 'ed25519'
    - name: www ownership
      ansible.builtin.file:
        path: /var/www
        owner: deploy
        group: www-data
        recurse: yes

    # postgresql backups
    - name: backups dir
      ansible.builtin.file:
        path: /home/deploy/backups
        state: directory
        mode: '0755'
      become_user: deploy
    - name: Add job to crontab
      ansible.builtin.cron:
        name: backup postgres dump
        minute: "55"
        hour: "11"
        job: "PGPASSWORD={{ pgpassword }} /var/www/shared-futures-space/backup-database.sh"
      become_user: deploy

    # repository
    - name: clone
      ansible.builtin.git:
        repo: https://github.com/animorphcoop/shared-futures-space
        dest: /var/www/shared-futures-space
        version: development
      become_user: deploy
    - name: dependencies
      ansible.builtin.pip:
        virtualenv_command: python3 -m venv
        virtualenv: /var/www/shared-futures-space/venv
        requirements: /var/www/shared-futures-space/requirements.txt
      become_user: deploy
    - name: npm
      community.general.npm:
        path: /var/www/shared-futures-space
      become_user: deploy
    - name: clear working dir
      # we discard changes because npm install changes package-lock.json
      ansible.builtin.shell:
        cmd: git checkout -- .
        chdir: /var/www/shared-futures-space
      args:
        executable: /bin/bash
      become_user: deploy

    # systemd
    - name: mkdir uwsgi
      ansible.builtin.file:
        path: /etc/uwsgi
        state: directory
        mode: '0755'
    - name: uwsgi template
      ansible.builtin.template:
        src: sfs.uwsgi.ini.j2
        dest: /etc/uwsgi/sfs.uwsgi.ini
        owner: root
        group: root
        mode: '0644'
    - name: web systemd template
      ansible.builtin.template:
        src: sfs.service.j2
        dest: /etc/systemd/system/sfs.service
        owner: root
        group: root
        mode: '0644'
    - name: worker systemd template
      ansible.builtin.template:
        src: sfsworker.service.j2
        dest: /etc/systemd/system/sfsworker.service
        owner: root
        group: root
        mode: '0644'
    - name: systemd reload
      ansible.builtin.systemd:
        daemon_reload: true
    - name: web systemd enable
      ansible.builtin.systemd:
        name: sfs
        enabled: yes
    - name: web systemd start
      ansible.builtin.systemd:
        name: sfs
        state: restarted
    - name: worker systemd enable
      ansible.builtin.systemd:
        name: sfsworker
        enabled: yes
    - name: worker systemd start
      ansible.builtin.systemd:
        name: sfsworker
        state: restarted

    # deployment specific
    - name: npm run build
      ansible.builtin.shell:
        cmd: npm run build
        chdir: /var/www/shared-futures-space
      args:
        executable: /bin/bash
      become_user: deploy
    - name: collectstatic
      ansible.builtin.shell:
        cmd: |
          source venv/bin/activate
          python3 manage.py collectstatic --no-input
        chdir: /var/www/shared-futures-space
      args:
        executable: /bin/bash
      become_user: deploy
    - name: migrations
      ansible.builtin.shell:
        cmd: |
          source venv/bin/activate
          export DB_HOST=localhost
          export POSTGRES_DB=sfs_db
          export POSTGRES_USER=sfs_user
          export PGPASSWORD={{ pgpassword }}
          python3 manage.py migrate
        chdir: /var/www/shared-futures-space
      args:
        executable: /bin/bash
      become_user: deploy
    - name: uwsgi restart
      ansible.builtin.systemd:
        name: sfs
        state: restarted
    - name: caddy restart
      ansible.builtin.systemd:
        name: caddy
        state: restarted
